package com.getz.setthegoal.di

object ModulesNames {
    const val NETWORK_MODULE = "NETWORK_MODULE"
    const val INTERCEPTOR_MODULE = "INTERCEPTOR_MODULE"
    const val DOMAIN_TRANSFORMER_MODULE = "DOMAIN_TRANSFORMER_MODULE"
    const val VIEW_MODEL_MODULE = "VIEW_MODEL_MODULE"
    const val FACTORY_VIEW_MODEL_MODULE = "FACTORY_VIEW_MODEL_MODULE"
    const val REPOSITORY_MODULE = "REPOSITORY_MODULE"
    const val DATA_SOURCE_MODULE = "DATA_SOURCE_MODULE"
}