package com.getz.setthegoal.di

object ModulesNames {
    const val NETWORK_MODULE = "NETWORK_MODULE"
    const val INTERCEPTOR_MODULE = "INTERCEPTOR_MODULE"
    const val MAPPER_MODULE = "MAPPER_MODULE"
    const val DATA_TO_DOMAIN_MAPPER_MODULE = "DATA_TO_DOMAIN_MAPPER_MODULE"
    const val PRESENT_TO_DOMAIN_MAPPER_MODULE = "PRESENT_TO_DOMAIN_MAPPER_MODULE"
    const val DOMAIN_TO_DATA_MAPPER_MODULE = "DOMAIN_TO_DATA_MAPPER_MODULE"
    const val DOMAIN_TO_PRESENT_MAPPER_MODULE = "DOMAIN_TO_PRESENT_MAPPER_MODULE"
    const val VIEW_MODEL_MODULE = "VIEW_MODEL_MODULE"
    const val FACTORY_VIEW_MODEL_MODULE = "FACTORY_VIEW_MODEL_MODULE"
    const val REPOSITORY_MODULE = "REPOSITORY_MODULE"
    const val DATA_SOURCE_MODULE = "DATA_SOURCE_MODULE"
    const val USE_CASE_MODULE = "USE_CASE_MODULE"
    const val TRANSLATOR_MODULE = "TRANSLATOR_MODULE"
    const val FIRESTORE_MODULE = "FIRESTORE_MODULE"
    const val CONNECTION_MODULE = "CONNECTION_MODULE"
}